import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./themeColor";
import Navbar from "./components/navbar/Navbar";
import { AuthLoggedProvider } from "./context/AuthContext";
import { FavoritesProvider } from "./context/FavoritesCartsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <AuthLoggedProvider>
            <FavoritesProvider>
              <ThemeProvider theme={theme}>
                <Navbar />
                {children}
              </ThemeProvider>
            </FavoritesProvider>
          </AuthLoggedProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
